name: Update README with Repos

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Repositories and Update README
        run: |
          curl -s https://api.github.com/users/Negi97Mohit/repos | jq -r '.[] | "- [\(.name)](\(.html_url)) - \(.description // "No description")"' > repos.md
          echo -e "# Hello, I'm Mohit Singh Negi\n\n$(cat repos.md)" > README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update README with repositories'
          git push
